---
title: "Extereme Temperature analysis"
author: "Isack Walube"
date: "2024/05/03"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{IsackW_ExtremeTEMP}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


### Packages 
```{r}
library(terra)
library(dplyr)
library(sf)
```
 
### 
```{r, eval=F}
climate_rast18 <- rast(here::here("5_year_highRes/2018_hiRes.tif"))
tmax_2018 <- climate_rast18$tasmax - 273.15

climate_rast19 <- rast(here::here("5_year_highRes/2019_hiRes.tif"))
tmax_2019 <- climate_rast19$tasmax - 273.15

climate_rast20 <- rast(here::here("5_year_highRes/2020_hiRes.tif"))
tmax_2020 <- climate_rast20$tasmax - 273.15

climate_rast21 <- rast(here::here("5_year_highRes/2021_hiRes.tif"))
tmax_2021 <- climate_rast21$tasmax - 273.15

climate_rast22 <- rast(here::here("5_year_highRes/2022_hiRes.tif"))
tmax_2022 <- climate_rast22$tasmax - 273.15

climate_rast23 <- rast(here::here("5_year_highRes/2023_hiRes.tif"))
tmax_2023 <- climate_rast23$tasmax - 273.15

maxtemp_6y <- rast(list(tmax_2018, tmax_2019, tmax_2020, tmax_2021,
                     tmax_2022, tmax_2023))
names(maxtemp_6y) <- c("2018", "2019", "2020", "2021", "2022", "2023")

plot(maxtemp_6y, axes = FALSE, mar = c(1, 1, 2,3))

maxtemp_6y <- rast(list(tmax_2018, tmax_2019, tmax_2020, tmax_2021,
                     tmax_2022, tmax_2023))
names(maxtemp_6y) <- c("2018", "2019", "2020", "2021", "2022", "2023")

plot(maxtemp_6y, axes = FALSE, mar = c(1, 1, 2,3))
```



```{r, eval=F}
# read in the regions
us_region$geometry <- read_sf("../states/States_shapefile.shp") 
# filter regions
northeast <- filter(us_region, Region =="Northeast") %>% select(State_Name)
south <- filter(us_region, Region =="South") %>% select(State_Name)
west <- filter(us_region, Region =="West") %>% select(State_Name)
midwest <- filter(us_region, Region =="Midwest") %>% select(State_Name)
```



```{r, eval=F, fig.width=6, fig.height=5}
tmax_ne_6y <- crop(maxtemp_6y, northeast, mask = F)
plot(tmax_ne_6y, axes = FALSE, mar = c(1, 1, 2, 3))


tmax_mdw_6y <- crop(maxtemp_6y, midwest, mask = TRUE)
plot(tmax_mdw_6y, axes = FALSE, mar = c(1, 1, 4, 5))


tmax_s_6y <- crop(maxtemp_6y, south, mask = TRUE)
plot(tmax_s_6y, axes = FALSE, mar = c(1, 1, 4, 6))

tmax_w_6y <- crop(maxtemp_6y, west, mask = TRUE)
plot(tmax_w_6y, axes = FALSE, mar = c(1, 1, 2, 3))
```


```{r, eval=F fig.width=6, fig.height=5}
# Calculate the 90th percentile, filter the values above the 90th percentile and plot
above_90th_northe <- tmax_ne_6y > unlist(global(tmax_ne_6y, 
                                                probs = 0.9, na.rm = TRUE))

par(mfrow = c(2, 3), mar = c(0, 0, 1, 0))
lapply(1:6, function(x){
  plot(above_90th_northe[[x]], axes = F, main = names(above_90th_northe[[x]]))
  plot(northeast, add = TRUE, col = rgb(0, 0, 0, 0))
})


above_90th_mdwest <- tmax_mdw_6y > unlist(global(tmax_mdw_6y, 
                                                  probs = 0.9, na.rm = TRUE))

par(mfrow = c(2, 3), mar = c(0, 0, 1, 0))
lapply(1:6, function(x){
  plot(above_90th_mdwest[[x]], axes = F, main = names(above_90th_mdwest[[x]]))
  plot(midwest, add = TRUE, col = rgb(0, 0, 0, 0))
})


above_90th_south <- tmax_s_6y > unlist(global(tmax_s_6y, 
                                               probs = 0.9, na.rm = TRUE))

par(mfrow = c(2, 3), mar = c(0, 0, 1, 0))
lapply(1:6, function(x){
  plot(above_90th_south[[x]], axes = F, main = names(above_90th_south[[x]]))
  plot(south, add = TRUE, col = rgb(0, 0, 0, 0))
})


above_90th_west <- tmax_w_6y > unlist(global(tmax_w_6y, 
                                               probs = 0.9, na.rm = TRUE))

par(mfrow = c(2, 3), mar = c(0, 0, 1, 0))
lapply(1:6, function(x){
  plot(above_90th_west[[x]], axes = F, main = names(above_90th_west[[x]]))
  plot(west, add = TRUE, col = rgb(0, 0, 0, 0))
})
```


```{r, eval=F, fig.width=6, fig.height=5}
climate_rast18 <- rast(here::here("5_year_highRes/2018_hiRes.tif"))
tmin_2018 <- climate_rast18$tasmin - 273.15

climate_rast19 <- rast(here::here("5_year_highRes/2019_hiRes.tif"))
tmin_2019 <- climate_rast19$tasmin - 273.15

climate_rast20 <- rast(here::here("5_year_highRes/2020_hiRes.tif"))
tmin_2020 <- climate_rast20$tasmin - 273.15

climate_rast21 <- rast(here::here("5_year_highRes/2021_hiRes.tif"))
tmin_2021 <- climate_rast21$tasmin - 273.15

climate_rast22 <- rast(here::here("5_year_highRes/2022_hiRes.tif"))
tmin_2022 <- climate_rast22$tasmin - 273.15

climate_rast23 <- rast(here::here("5_year_highRes/2023_hiRes.tif"))
tmin_2023 <- climate_rast23$tasmin - 273.15

mintemp_6y <- rast(list(tmin_2018, tmin_2019, tmin_2020, tmin_2021,
                     tmin_2022, tmin_2023))
names(mintemp_6y) <- c("2018", "2019", "2020", "2021", "2022", "2023")

plot(mintemp_6y, axes = FALSE, mar = c(1, 1, 2, 3))
```

```{r, eval=F, fig.width=6, fig.height=5}
#crop raster by region and plot
tmin_ne_6y <- crop(mintemp_6y, northeast, mask = TRUE)
plot(tmin_ne_6y, axes = FALSE, mar = c(1, 1, 2,3))

tmin_mdwst_6y <- crop(mintemp_6y, midwest, mask = TRUE)
plot(tmin_ne_6y, axes = FALSE, mar = c(1, 1, 2,3))

tmin_s_6y <- crop(mintemp_6y, south, mask = TRUE)
plot(tmin_ne_6y, axes = FALSE, mar = c(1, 1, 2, 3))

tmin_w_6y <- crop(mintemp_6y, west, mask = TRUE)
plot(tmin_ne_6y, axes = FALSE, mar = c(1, 1, 2,3))
```

```{r, eval=F, fig.width=6, fig.height=5}
# Calculate the 90th percentile, filter the values above the 90th percentile and plot
below_10th_northe <- tmin_ne_6y < unlist(global(tmin_ne_6y, 
                                               probs = 0.1, na.rm = TRUE))
par(mfrow = c(2, 3), mar = c(0, 0, 1, 0))
lapply(1:6, function(x){
  plot(below_10th_northe[[x]], axes = F, main = names(below_10th_northe[[x]]))
  plot(northeast, add = TRUE, col = rgb(0, 0, 0, 0))
})


below_10th_mdwest <- tmin_mdwst_6y < unlist(global(tmin_mdwst_6y, 
                                               probs = 0.1, na.rm = TRUE))
par(mfrow = c(2, 3), mar = c(0, 0, 1, 0))
lapply(1:6, function(x){
  plot(below_10th_mdwest[[x]], axes = F, main = names(below_10th_mdwest[[x]]))
  plot(midwest, add = TRUE, col = rgb(0, 0, 0, 0))
})



below_10th_south <- tmin_s_6y < unlist(global(tmin_s_6y, 
                                               probs = 0.1, na.rm = TRUE))
par(mfrow = c(2, 3), mar = c(0, 0, 1, 0))
lapply(1:6, function(x){
  plot(below_10th_south[[x]], axes = F, main = names(below_10th_south[[x]]))
  plot(south, add = TRUE, col = rgb(0, 0, 0, 0))
})


below_10th_west <- tmin_w_6y < unlist(global(tmin_w_6y, 
                                               probs = 0.1, na.rm = TRUE))
par(mfrow = c(2, 3), mar = c(0, 0, 1, 0))
lapply(1:6, function(x){
  plot(below_10th_west[[x]], axes = F, main = names(below_10th_west[[x]]))
  plot(west, add = TRUE, col = rgb(0, 0, 0, 0))
})
```


































